# Generated by Django 5.2.6 on 2025-09-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='watch_images/'),
        ),
    ]
