# Generated by Django 5.2.6 on 2025-09-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_watch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
